// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJQ52NelxADKUxa03LXsYpAjT7oDCsdXY',
    appId: '1:195085744714:web:d7ef8bc899980378b3c4b3',
    messagingSenderId: '195085744714',
    projectId: 'womenconnect-ecc5b',
    authDomain: 'womenconnect-ecc5b.firebaseapp.com',
    storageBucket: 'womenconnect-ecc5b.firebasestorage.app',
    measurementId: 'G-8N3VDBETLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnxDt1KHiczRaK9VKv-esLcmlP4HTMn6Q',
    appId: '1:195085744714:android:98f5a7e52b4ca48fb3c4b3',
    messagingSenderId: '195085744714',
    projectId: 'womenconnect-ecc5b',
    storageBucket: 'womenconnect-ecc5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Y25D1r5WE6CS8b00JeQ8EReBag32iro',
    appId: '1:195085744714:ios:4ed13ca8166906e9b3c4b3',
    messagingSenderId: '195085744714',
    projectId: 'womenconnect-ecc5b',
    storageBucket: 'womenconnect-ecc5b.firebasestorage.app',
    iosBundleId: 'com.example.womenconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Y25D1r5WE6CS8b00JeQ8EReBag32iro',
    appId: '1:195085744714:ios:4ed13ca8166906e9b3c4b3',
    messagingSenderId: '195085744714',
    projectId: 'womenconnect-ecc5b',
    storageBucket: 'womenconnect-ecc5b.firebasestorage.app',
    iosBundleId: 'com.example.womenconnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJQ52NelxADKUxa03LXsYpAjT7oDCsdXY',
    appId: '1:195085744714:web:3d1fd4f0eaa755e4b3c4b3',
    messagingSenderId: '195085744714',
    projectId: 'womenconnect-ecc5b',
    authDomain: 'womenconnect-ecc5b.firebaseapp.com',
    storageBucket: 'womenconnect-ecc5b.firebasestorage.app',
    measurementId: 'G-Q4Q85RTN7L',
  );
}
